# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "uniflight"
description = "Deduplicates async tasks into a single execution."
version = "0.1.0"
readme = "README.md"
keywords = ["oxidizer", "coalescing", "stempede", "singleflight", "deduplication"]
categories = ["concurrency"]

edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
parking_lot.workspace = true
thread_aware = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
futures-util = { workspace = true, features = ["alloc", "std"] }
tokio = { workspace = true, features = ["macros", "rt", "time", "rt-multi-thread"] }

[lints]
workspace = true
